version: "3.5"
services:
  trino:
    ports:
      - "8080:8080"
    image: "starburstdata/starburst-enterprise:379-e"
    volumes:
      - ./docker/starburst/etc:/etc/starburst
      - ./docker/starburst/catalog:/etc/starburst/catalog

  postgres:
    ports:
      - "5432:5432"
    image: postgres:11
    environment:
      POSTGRES_USER: dbt-trino
      POSTGRES_PASSWORD: dbt-trino

networks:
  default:
    external:
      name: dbt-net
