name: dbt-trino tests
on:
  push:
    branches:
      - master
    paths-ignore:
      - "**/*.md"
  pull_request:
    branches:
      - master
    paths-ignore:
      - "**/*.md"

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout the source code"
        uses: actions/checkout@v2

      - name: "Install Python"
        uses: actions/setup-python@v2

      - name: "Install dev requirements"
        run: pip install -r dev_requirements.txt

      - name: "Run pre-commit checks"
        run: pre-commit run --all-files
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        engine:
          - "trino"
          - "starburst"
          - "starburst_galaxy"
        python:
          - "3.9"
          - "3.10"
        exclude:
          - engine: "starburst_galaxy"
            python: "3.10"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Run dbt-trino tests against ${{ matrix.engine }} on python ${{ matrix.python }}
        env:
          DBT_TESTS_STARBURST_GALAXY_HOST: ${{ secrets.DBT_TESTS_STARBURST_GALAXY_HOST }}
          DBT_TESTS_STARBURST_GALAXY_USER: ${{ secrets.DBT_TESTS_STARBURST_GALAXY_USER }}
          DBT_TESTS_STARBURST_GALAXY_PASSWORD: ${{ secrets.DBT_TESTS_STARBURST_GALAXY_PASSWORD }}
        run: |
          if [[ ${{ matrix.engine }} == "trino" || ${{ matrix.engine }} == "starburst" ]]; then
            make dbt-${{ matrix.engine }}-tests
          elif [[ ${{ matrix.engine }} == "starburst_galaxy" ]]; then
            python -m pip install -r dev_requirements.txt
            pip install -e .
            python -m pytest tests/functional --profile starburst_galaxy
          fi

      - name: Remove container on failure
        if: failure()
        run: ./docker/remove_${{ matrix.engine }}.bash || true
