name: dbt-trino tests
on:
  push:
    branches:
      - master
      - "*.*.latest"
    paths-ignore:
      - "**/*.md"
  pull_request:
    branches:
      - master
      - "*.*.latest"
    paths-ignore:
      - "**/*.md"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        type:
          - "trino"
          - "starburst"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Run dbt-trino tests against ${{ matrix.type }}
        run: make dbt-${{ matrix.type }}-tests

      - name: Remove container on failure
        if: failure()
        run: ./docker/remove_${{ matrix.type }}.bash || true
