name: dbt-trino tests
on:
  push:
    branches:
      - master
    paths-ignore:
      - "**/*.md"
  pull_request:
    branches:
      - master
    paths-ignore:
      - "**/*.md"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        engine:
          - "trino"
          - "starburst"
        python:
          - "3.9"
          - "3.10"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Run dbt-trino tests against ${{ matrix.engine }} on python ${{ matrix.python }}
        run: make dbt-${{ matrix.engine }}-tests

      - name: Remove container on failure
        if: failure()
        run: ./docker/remove_${{ matrix.engine }}.bash || true
